//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiverPoints.Business.Model.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiversPointsEntities : DbContext
    {
        public RiversPointsEntities()
            : base("name=RiversPointsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<River> Rivers { get; set; }
        public virtual DbSet<RiverSettlement> RiverSettlements { get; set; }
        public virtual DbSet<Settlement> Settlements { get; set; }
        public virtual DbSet<UserRoll> UserRolls { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
