//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiverPoints.Business.Model.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiverSettlement
    {
        public int Id { get; set; }
        public Nullable<int> FKRiverID { get; set; }
        public Nullable<int> FKSettlementID { get; set; }
        public Nullable<decimal> MaxDiameter { get; set; }
        public Nullable<int> FKPointID { get; set; }
        public Nullable<decimal> RecordDiameter { get; set; }
    }
}
